# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Joseph's 筆記
tagline:          'A Jekyll theme'
description:      ''
url:              https://josephjsf.github.io/
baseurl:          "/"

author:
  name:           'Joseph'
  url:            https://josephjsf.github.io/

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/josephjsf


paginate_path: "page:num"
plugins: [jekyll-paginate, jekyll-gist]

# read more tag
excerpt_separator: <!--more-->